import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navigation/nav-bar";
import { verifyAuth } from "@/lib/auth";
import { getCurrentUser } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const result = await verifyAuth();
  let isLoggedIn;
  // unathenticated user
  if (!result.user) {
    isLoggedIn = false;
  } else {
    isLoggedIn = true;
  }

  let profileData = null;

  const sessionUser = await getCurrentUser();
  if (!sessionUser) {
    // not logged in
  } else {
    // sessionUser.user contains sanitized user info (no password)
    console.log(sessionUser);
    profileData = sessionUser;
  }

  

  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavigationBar isLoggedIn={isLoggedIn} profileData={profileData}/>
        {children}
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
